name: probe_design
channels:
  - bioconda
dependencies:
  - python=3.7
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - jupyter
  - bowtie2
  - samtools
  - blast
  - pysam
  - pip:
      - pyfaidx
      - biopython
      - fire
      - toolz
      - cytoolz
      - bramin==0.0.1
      - intervaltree
